name: Deploy Contoso_University_Core

on:
  workflow_run:
    workflows: ["Pack Contoso_University_Core"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: created pack-solution.yml
          name: packed-solution
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: https://org4f7aea94.crm.dynamics.com
          app-id: ${{ secrets.PP_APP_ID }}
          client-secret: ${{ secrets.PP_CLIENT_SECRET }}
          tenant-id: ${{ secrets.PP_TENANT_ID }}
          solution-file: contoso_university_core.zip
